# ======
# Project Details
# ======
name: 'dbt_demo'
version: '1.0'
config-version: 2
profile: 'dbt_demo'
require-dbt-version: 1.2.0

# ======
# File Path Configs
# ======
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

# ==================
# Model Configs
# ==================
models:

  bronze:
    +schema: 'bronze'
  silver:
    +schema: 'silver'
  golden:
    +schema: 'golden'
