config:

  partial_parse: true
dbt_demo:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: service_account.json
      project: elegant-tendril-362907
      dataset: instacart
      threads: 2

      
